name: Build and Deploy
on: [push]

jobs:
  #build and test then deploy frontend
  build-and-test-then-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.13.0'

      - name: Build project
        run: yarn install && npm run build

      ## ce job vise à exécuter le test de cypress mais je le désactive car il utilisera beaucoup de mémoire dans les runners de azure
      ## et il y a des chances qu'il se plante
      #- name: launch cypress test
        #run: npm run test

      - name: Export Static files
        run: npm run export    # runs `next export`
        env:
          CI: true
          DEPLOY_TARGET: gh-pages

      - name: configure host folder
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: client/out       # The folder the action should deploy.
          CLEAN: true       # Automatically remove deleted files from the deploy branch